language: c

matrix:
  include:
    - name: "Ubuntu 16.04 (Xenial)"
      os: linux
      dist: xenial

    - name: "Ubuntu 18.04 (Bionic)"
      os: linux
      dist: bionic

    - name: "MacOS 10.13 / Xcode 9"
      os: osx
      osx_image: xcode9.4

    - name: "MacOS 10.14 / Xcode 11"
      os: osx
      osx_image: xcode11.3

    - name: "Windows"
      os: windows

script:
  - bash ./travis-environment-probe
